chore: release main
cap-js/cds-dbs pull request #494
Opened 2024-03-05 09:31 UTC by cap-bots

:robot: I have created a release *beep* *boop*
---

<details><summary>db-service: 1.6.5</summary>

## [1.6.5](https://github.com/cap-js/cds-dbs/compare/db-service-v1.6.4...db-service-v1.6.5) (2024-03-05)

### Fixed

* deep delete for views without navigation ([#434](https://github.com/cap-js/cds-dbs/issues/434)) ([3ebc9c2](https://github.com/cap-js/cds-dbs/commit/3ebc9c29362045916c9060528729320c0eae4391))
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

2024-03-05 12:18 UTC, patricebender commented on db-service/CHANGELOG.md
> +* deep delete for views without navigation ([#434](https://github.com/cap-js/cds-dbs/issues/434)) ([3ebc9c2](https://github.com/cap-js/cds-dbs/commit/3ebc9c29362045916c9060528729320c0eae4391))
remove before release

2024-03-06 14:31 UTC, patricebender requested changes

2024-03-06 14:31 UTC, patricebender commented on db-service/CHANGELOG.md
> +* deep delete for views without navigation ([#434](https://github.com/cap-js/cds-dbs/issues/434)) ([3ebc9c2](https://github.com/cap-js/cds-dbs/commit/3ebc9c29362045916c9060528729320c0eae4391))
remove before release ([release-please does not do this for us](https://github.com/googleapis/release-please/issues/296))

2024-03-12 09:26 UTC, patricebender commented on hana/CHANGELOG.md
> +
we need to add https://github.com/cap-js/cds-dbs/pull/488 → release please seems to be buggy if a conventional commit contains code fences as described here: https://github.com/googleapis/release-please/issues/2020

2024-03-20 13:00 UTC, johannes-vogel commented
I think we also need to increase peer dependency versions with this release.

2024-03-22 13:24 UTC, patricebender approved these changes

2024-03-22 13:37 UTC, merged

2024-03-22 13:37 UTC, johannes-vogel commented
@patricebender Do we also need to update the PR description for the release tags?

2024-03-22 13:37 UTC, cap-bots commented
:robot: Release is at https://github.com/cap-js/cds-dbs/releases/tag/db-service-v1.7.0 :sunflower:

2024-03-22 13:37 UTC, cap-bots commented
:robot: Release is at https://github.com/cap-js/cds-dbs/releases/tag/sqlite-v1.6.0 :sunflower:

2024-03-22 13:37 UTC, cap-bots commented
:robot: Release is at https://github.com/cap-js/cds-dbs/releases/tag/postgres-v1.6.0 :sunflower:

2024-03-22 13:37 UTC, cap-bots commented
:robot: Release is at https://github.com/cap-js/cds-dbs/releases/tag/hana-v0.1.0 :sunflower: