chore: release main
cap-js/cds-dbs pull request #743
Opened 2024-07-11 16:11 UTC by cap-bots

:robot: I have created a release *beep* *boop*
---

<details><summary>sqlite: 1.7.4</summary>

## [1.7.4](https://github.com/cap-js/cds-dbs/compare/sqlite-v1.7.3...sqlite-v1.7.4) (2024-07-11)

### Fixed

* enforce db file to be existent before server start ([#742](https://github.com/cap-js/cds-dbs/issues/742)) ([64a9018](https://github.com/cap-js/cds-dbs/commit/64a90186aaf44b3426df2e9adbf9a1b4cf2f92b7))
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

2024-07-12 08:21 UTC, johannes-vogel commented on sqlite/CHANGELOG.md
> +* enforce db file to be existent before server start ([#742](https://github.com/cap-js/cds-dbs/issues/742)) ([64a9018](https://github.com/cap-js/cds-dbs/commit/64a90186aaf44b3426df2e9adbf9a1b4cf2f92b
needs to be removed manually due to revert

2024-07-19 13:48 UTC, patricebender commented on db-service/CHANGELOG.md
something went badly wrong with this changelog

2024-07-22 08:43 UTC, patricebender requested changes
db service changelog is broken

2024-07-25 11:04 UTC, johannes-vogel commented on .release-please-manifest.json
> +  "postgres": "1.9.2",
```suggestion
  "postgres": "1.10.0",
```

2024-07-25 11:05 UTC, johannes-vogel commented on .release-please-manifest.json
> +  "sqlite": "1.7.4",
```suggestion
```

2024-07-25 13:04 UTC, patricebender approved these changes

2024-07-25 13:12 UTC, merged

2024-07-25 13:12 UTC, cap-bots commented
:robot: Created releases:
- [db-service-v1.12.0](https://github.com/cap-js/cds-dbs/releases/tag/db-service-v1.12.0)
- [postgres-v1.9.2](https://github.com/cap-js/cds-dbs/releases/tag/postgres-v1.9.2)
- [hana-v1.1.1](https://github.com/cap-js/cds-dbs/releases/tag/hana-v1.1.1)
:sunflower: