fix view resolving for stream
cap-js/cds-dbs pull request #96
Opened 2023-07-07 12:50 UTC by SamuelBrucksch

2023-07-10 08:41 UTC, sjvans commented on db-service/lib/SQLService.js
> +
```suggestion
    if (cmd in { INSERT: 1, DELETE: 1, UPSERT: 1, UPDATE: 1 } || cqn.STREAM?.into) {
```
wouldn't this do the same?

2023-07-10 08:41 UTC, sjvans requested changes
see https://github.com/cap-js/cds-dbs/pull/96/files#r1257918662

2023-07-11 09:10 UTC, sjvans approved these changes
🏂

2023-07-11 15:00 UTC, BobdenOs approved these changes

2023-07-27 08:54 UTC, johannes-vogel commented
we should also increase the peer dependency version as streaming does not work without the cds fix, shouldn't we?

2023-07-31 12:52 UTC, sjvans commented on db-service/package.json
> +    "@sap/cds": ">=7.1.0"
```suggestion
    "@sap/cds": ">=7.1.1"
```

2023-07-31 21:13 UTC, sjvans commented on package-lock.json
> +      "version": "7.1.0",
update needed

2023-07-31 21:46 UTC, sjvans commented on db-service/CHANGELOG.md
> +- View resolving for streams
```suggestion
- View resolving for streams.
```

2023-08-01 14:19 UTC, merged